trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 2.2.100

- task: NuGetToolInstaller@0
  displayName: 'Installing Nuget Tools...'
  inputs:
    versionSpec: '4.9.2'

- script: dotnet build --configuration $(buildConfiguration) src/Blazored.Modal/Blazored.Modal.csproj
  displayName: 'Building $(buildConfiguration)...'

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts...'