name: Release

on:
  release:
    types: [ published ]

env:
    NETCORE_VERSION: '3.1.301'
    BRANCH: 'main'

jobs:
  build:
    name: Build, test and pack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setting up .NET Core SDK ${{ env.NETCORE_VERSION }}...
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restoring packages...
      run: dotnet restore

    - name: Building project...
      run: dotnet build --configuration Release --no-restore src/Blazored.Modal/Blazored.Modal.csproj

    - name: Testing...
      run: dotnet test --no-restore --verbosity normal

    - name: Creating NuGet package...
      run: dotnet pack src/Blazored.Modal/ -c Release -o ${GITHUB_WORKSPACE}/packages

    - name: Push package to NuGET
      run: dotnet nuget push ${GITHUB_WORKSPACE}/packages/'*.nupkg' -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
